services:
  - type: web
    name: smart-energy-controller
    runtime: node
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: ESP32_API_URL
        value: https://smart-energy-controller-knb7.onrender.com
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - smart-energy-controller.onrender.com
